{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minimax.opensdk_android",
    "module": "voice_call",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b5irpdfsa5egjdgxvrzgr4kqbe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voice_call-1.0.0.aar",
          "url": "voice_call-1.0.0.aar",
          "size": 203431,
          "sha512": "69797bd65344a9a8f4c4fdcbde8ff34268919fa6d053fd55e221b665416c30c87db430a726ef168675768dda56fd6bf6573fbc3e824caa645d2d8d3abc9a1ecc",
          "sha256": "30192ef839509fe1789678aea93d17ecd5b85d31c5315fef50fb606aac120bfc",
          "sha1": "6a0f4238db25402f79385eb1e5ebad2cd8373103",
          "md5": "cc36962ce5563aa7775940168f9c70a4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.minimax.opensdk_android",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.github.gkonovalov.android-vad",
          "module": "webrtc",
          "version": {
            "requires": "2.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "voice_call-1.0.0.aar",
          "url": "voice_call-1.0.0.aar",
          "size": 203431,
          "sha512": "69797bd65344a9a8f4c4fdcbde8ff34268919fa6d053fd55e221b665416c30c87db430a726ef168675768dda56fd6bf6573fbc3e824caa645d2d8d3abc9a1ecc",
          "sha256": "30192ef839509fe1789678aea93d17ecd5b85d31c5315fef50fb606aac120bfc",
          "sha1": "6a0f4238db25402f79385eb1e5ebad2cd8373103",
          "md5": "cc36962ce5563aa7775940168f9c70a4"
        }
      ]
    }
  ]
}
