{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minimax.opensdk_android",
    "module": "voice_call",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ihgmmyncnfgcpkpuheqm7evzre"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voice_call-1.0.0.aar",
          "url": "voice_call-1.0.0.aar",
          "size": 203286,
          "sha512": "9944b69e08530f1b12165a5cf4a87046707e8aa28045cfedc940b17fc24143bc827e0d085fec459150771581f70253b6fbc6880e521f58a796609997953d44fb",
          "sha256": "06d354dede9e65fac64fde9ed1310e9eaa86d99a3b2bc9945235d63803015779",
          "sha1": "863586fcf9531c77d1116591aa525ac1f9940891",
          "md5": "fe0f8e7718c14b607d39f931e5819ba2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.minimax.opensdk_android",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.github.gkonovalov.android-vad",
          "module": "webrtc",
          "version": {
            "requires": "2.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "voice_call-1.0.0.aar",
          "url": "voice_call-1.0.0.aar",
          "size": 203286,
          "sha512": "9944b69e08530f1b12165a5cf4a87046707e8aa28045cfedc940b17fc24143bc827e0d085fec459150771581f70253b6fbc6880e521f58a796609997953d44fb",
          "sha256": "06d354dede9e65fac64fde9ed1310e9eaa86d99a3b2bc9945235d63803015779",
          "sha1": "863586fcf9531c77d1116591aa525ac1f9940891",
          "md5": "fe0f8e7718c14b607d39f931e5819ba2"
        }
      ]
    }
  ]
}
