{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minimax.opensdk_android",
    "module": "voice_call",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cyh7izhmbrfnxiglkcj3w6yk7i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voice_call-1.0.3.aar",
          "url": "voice_call-1.0.3.aar",
          "size": 214624,
          "sha512": "e0b2ce7d3158ca6a275031f82e82a31ce44bacfe3fde1f824fab4bfc2cbf1676c75d3d165194a17dc4db62f919e8cdb7c0cf45838675062b91b7eeaf6be86a79",
          "sha256": "0c9d8965bbf1a4d82fe7eb971a5b63d125ca3b6ebad237ea21fcf02d317352fb",
          "sha1": "89f42fb003eda5b55acf61ea1a5ebf96996c28e5",
          "md5": "7dd1eae71120e4e0a343b6d13ea5da51"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.minimax.opensdk_android",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.github.gkonovalov.android-vad",
          "module": "webrtc",
          "version": {
            "requires": "2.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "voice_call-1.0.3.aar",
          "url": "voice_call-1.0.3.aar",
          "size": 214624,
          "sha512": "e0b2ce7d3158ca6a275031f82e82a31ce44bacfe3fde1f824fab4bfc2cbf1676c75d3d165194a17dc4db62f919e8cdb7c0cf45838675062b91b7eeaf6be86a79",
          "sha256": "0c9d8965bbf1a4d82fe7eb971a5b63d125ca3b6ebad237ea21fcf02d317352fb",
          "sha1": "89f42fb003eda5b55acf61ea1a5ebf96996c28e5",
          "md5": "7dd1eae71120e4e0a343b6d13ea5da51"
        }
      ]
    }
  ]
}
