{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minimax.opensdk_android",
    "module": "voice_call",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "v3pyjlrs5vabpklsxyb74kkrta"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voice_call-1.0.1.aar",
          "url": "voice_call-1.0.1.aar",
          "size": 205029,
          "sha512": "b1a126bb821060d996ee838e0634c4619d53f9a301f8cddee4ccea094f419bab9ebcc19672127aa93a221bf5d410c0431577657be5129cad3b19bdf0b48c6d97",
          "sha256": "371b3129bab73f24f03f7a8148c88947cc3674e044602a6bfcc87a0e3a77c396",
          "sha1": "ee2e2adeb6097d3082d75ca528f96cb25327aad1",
          "md5": "2a44343429901960c68ab6fa5e3bd372"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.minimax.opensdk_android",
          "module": "network",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.github.gkonovalov.android-vad",
          "module": "webrtc",
          "version": {
            "requires": "2.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "excludes": [
            {
              "group": "org.jetbrains",
              "module": "annotations-java5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "voice_call-1.0.1.aar",
          "url": "voice_call-1.0.1.aar",
          "size": 205029,
          "sha512": "b1a126bb821060d996ee838e0634c4619d53f9a301f8cddee4ccea094f419bab9ebcc19672127aa93a221bf5d410c0431577657be5129cad3b19bdf0b48c6d97",
          "sha256": "371b3129bab73f24f03f7a8148c88947cc3674e044602a6bfcc87a0e3a77c396",
          "sha1": "ee2e2adeb6097d3082d75ca528f96cb25327aad1",
          "md5": "2a44343429901960c68ab6fa5e3bd372"
        }
      ]
    }
  ]
}
